### ISSUE TITLE
Redundant config？

### ISSUE THREAD

**Issue by zhengzx-nlp** [whr94621/NJUNMT-pytorch#14]
https://github.com/whr94621/NJUNMT-pytorch/blob/b598413ddf3e18e6ef1bf87453253217bd4a3aba/scripts/translate.sh#L13

https://github.com/whr94621/NJUNMT-pytorch/blob/b598413ddf3e18e6ef1bf87453253217bd4a3aba/scripts/translate.sh#L15

It seams to be of not necessity to provide src and tgt dicts since config.yaml has been provided.

**Comment by whr94621** [comment]
Ooh ! That's indeed not necessary. Please send a PR to fix this. :)

This issue relates to ```translate.py```

and ```src/main.py``` 
https://github.com/whr94621/NJUNMTpytorch/blob/b598413ddf3e18e6ef1bf87453253217bd4a3aba/src/main.py#L616

**Comment by zhaocq-nlp** [comment]
@zhengzx-nlp 
这个细节，只要允许额外的--target_dict_path覆盖config_path里的参数就好了，就跟你run一个控制台的命令，command后面的参数总能生效是一样的道理。
