### ISSUE TITLE
RuntimeError: "index_select_out_cuda_impl" not implemented for 'Float'

### ISSUE THREAD

**Issue by hoDuyAPCS** [whr94621/NJUNMT-pytorch#46]
Has anyone encounter this problem ? Any help is appreciated.

**Comment by hoDuyAPCS** [comment]
Got it while running beam_search.py. Also I don't understand what the comment #[batch_size, ] next to next_beam_ids mean

**Comment by vergilus** [comment]
> Got it while running beam_search.py. Also I don't understand what the comment #[batch_size, ] next to next_beam_ids mean

detailed error log pls?  I doubt there's something to do with the torch version.

**Comment by hoDuyAPCS** [comment]
Thanks for replying to my email. Here is the full error log
[image: image.png]

**Comment by hoDuyAPCS** [comment]
Sorry, I should have sent this earlier. Full Error Log

- (Epc 0, Upd 20) : 3% 4095/120885 [00:27<18:41, 104.15sents/s, TrainLoss:
7.65, ValidLoss(best): 170.35 (170.35)] - (Infer) : 0% 0/1503 [00:00<?,
?sents/s]Traceback (most recent call last): File
"/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__",
mod_spec) File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals) File "/content/NJUNMT-pytorch/src/bin/train.py",
line 49, in <module> run() File "/content/NJUNMT-pytorch/src/bin/train.py",
line 45, in run train(args) File "/content/NJUNMT-pytorch/src/main.py",
line 655, in train alpha=training_configs["bleu_valid_configs"]["alpha"]
File "/content/NJUNMT-pytorch/src/main.py", line 239, in bleu_validation
word_ids = beam_search(nmt_model=model, beam_size=beam_size,
max_steps=max_steps, src_seqs=x, alpha=alpha) File
"/content/NJUNMT-pytorch/src/decoding/beam_search.py", line 94, in
beam_search gather_shape=[-1]) File
"/content/NJUNMT-pytorch/src/decoding/utils.py", line 87, in
tensor_gather_helper output =
torch.index_select(gather_from.view(*gather_shape), 0, gather_indices_)
RuntimeError: "index_select_out_cuda_impl" not implemented for 'Float' -
(Infer) : 0% 5/1503 [00:00<00:45, 33.23sents/s] - (Epc 0, Upd 20) : 3%
4095/120885 [00:31<15:00, 129.75sents/s, TrainLoss: 7.65, ValidLoss(best):
170.35 (170.35)]

**Comment by hoDuyAPCS** [comment]
Thank you very much, it was indeed the pytorch version.
